Sorting Environment
totvs/tds-monitor-frontend pull request #2
Opened 2020-01-28 19:03 UTC by bardez

Added sorting functionallity to "environment" table column

2020-02-12 20:27 UTC, rogeriorc requested changes
Boa tarde!
Desculpe a demora, poderia apenas verificar a necessidade das dependências incluídas no package.json?

2020-02-12 20:27 UTC, rogeriorc commented on package.json
> +		"events": "^3.0.0",
Essas dependências novas são realmente necessárias?

2020-02-12 21:20 UTC, bardez commented on package.json
> +		"events": "^3.0.0",
Boa tarde. Na verdade deixei passar de outros teste que fiz 🙊. Quer que eu faça um novo commit?

2020-02-12 21:57 UTC, rogeriorc commented on package.json
> +		"events": "^3.0.0",
Por favor, ae ja atualiza tambem o package-lock!

(remover do package.json, deletar o arquivo package-lock.json e a pasta node_modules, e entao npm install no projeto)

2020-02-13 13:38 UTC, bardez commented on package.json
> +		"events": "^3.0.0",
Feito!

2020-02-13 15:05 UTC, rogeriorc approved these changes

2020-02-13 15:06 UTC, merged